# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhesus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='repeat_conservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=45, null=True)),
                ('chr_edit_pos', models.BigIntegerField()),
                ('repeat', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
